"use client";

import { useEffect, useMemo, useState } from "react";
import { Ban, ClipboardPlus, Download, Pencil, Search } from "lucide-react";
import { useInventory } from "@/components/inventory/InventoryContext";
import { InventoryTransactionModal } from "@/components/inventory/InventoryTransactionModal";
import { SortHeader } from "@/components/inventory/SortHeader";
import { csvDownload, outstandingLoans } from "@/components/inventory/inventoryUtils";
import { formatDateID, formatQty, getMovementBadge } from "@/components/inventory/helpers";
import type { InventoryTransaction } from "@/components/inventory/types";

const PAGE_SIZE = 30;

export default function TransactionsPage() {
  const { transactions, items, loading, reverseTransaction, toast, user } = useInventory();
  const [query, setQuery] = useState("");
  const [type, setType] = useState(""); const [category, setCategory] = useState(""); const [itemId, setItemId] = useState(""); const [borrower, setBorrower] = useState("");
  const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [onlyOutstanding, setOnlyOutstanding] = useState(false);
  const [sort, setSort] = useState("transaction_date"); const [direction, setDirection] = useState<"asc" | "desc">("desc"); const [page, setPage] = useState(1);
  const [modal, setModal] = useState<{ open: boolean; transaction: InventoryTransaction | null }>({ open: false, transaction: null });
  const borrowers = [...new Set(transactions.map((row) => row.handled_by).filter(Boolean) as string[])].sort();
  const outstandingTransactionIds = new Set(items.flatMap((item) => outstandingLoans(item.id, transactions)).map((row) => row.id));

  const filtered = useMemo(() => transactions.filter((row) => {
    if (query && ![row.item_name, row.item_code, row.activity_name, row.handled_by, row.recorded_by, row.reversal_reason].some((v) => v?.toLowerCase().includes(query.toLowerCase()))) return false;
    if (type && row.type !== type) return false; if (category && row.item_category !== category) return false; if (itemId && row.item_id !== itemId) return false; if (borrower && row.handled_by !== borrower) return false;
    if (start && row.transaction_date < start) return false; if (end && row.transaction_date > end) return false;
    if (onlyOutstanding && !outstandingTransactionIds.has(row.id)) return false;
    return true;
  }).sort((a, b) => { const av = a[sort as keyof InventoryTransaction] ?? ""; const bv = b[sort as keyof InventoryTransaction] ?? ""; const result = typeof av === "number" ? Number(av) - Number(bv) : String(av).localeCompare(String(bv), "id"); return direction === "asc" ? result : -result; }), [transactions, query, type, category, itemId, borrower, start, end, onlyOutstanding, sort, direction, outstandingTransactionIds]);
  useEffect(() => setPage(1), [query, type, category, itemId, borrower, start, end, onlyOutstanding]);
  const visible = filtered.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE); const pages = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const effective = filtered.filter((row) => !row.reversed_at);
  const incoming = effective.filter((row) => ["Masuk", "Kembali"].includes(row.type) || (row.type === "Penyesuaian" && row.quantity > 0)).length;
  const outgoing = effective.filter((row) => ["Keluar", "Rusak", "Hilang"].includes(row.type) || (row.type === "Penyesuaian" && row.quantity < 0)).length;
  const onSort = (field: string) => { if (field === sort) setDirection((value) => value === "asc" ? "desc" : "asc"); else { setSort(field); setDirection("asc"); } };
  const exportCsv = () => csvDownload("riwayat-keluar-masuk.csv", ["Tanggal", "Kode", "Barang", "Kategori", "Jenis", "Jumlah", "Satuan", "Sifat Keluar", "Kegiatan", "Peminjam", "Rencana Kembali", "Dicatat Oleh", "Status", "Alasan Pembatalan", "Catatan"], filtered.map((row) => [row.transaction_date, row.item_code, row.item_name, row.item_category, row.type, row.quantity, row.item_unit, row.type === "Keluar" ? row.is_returnable ? "Dipinjam" : "Habis terpakai" : "", row.activity_name, row.handled_by, row.expected_return_date, row.recorded_by, row.reversed_at ? "Dibatalkan" : "Aktif", row.reversal_reason, row.notes]));
  async function reverse(row: InventoryTransaction) {
    const reason = window.prompt(`Alasan pembatalan catatan ${row.type} ${formatQty(row.quantity, row.item_unit)} untuk ${row.item_name}:`)?.trim();
    if (!reason) return;
    try { await reverseTransaction(row.id, reason); toast("Transaksi dibatalkan; jejak aslinya tetap tersimpan"); }
    catch (err) { toast(err instanceof Error ? err.message : "Gagal membatalkan transaksi", "error"); }
  }
  const canModify = (row: InventoryTransaction) => user.role === "admin" && !row.reversed_at && !row.stocktake_id;

  return <div className="mx-auto max-w-[1600px] p-4 sm:p-6 xl:p-8">
    <header className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold text-brand">Jejak pergerakan</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Riwayat Keluar-Masuk</h1><p className="mt-1 text-sm text-slate-500">Peminjam dan pencatat tersimpan terpisah; transaksi salah dibatalkan tanpa menghapus histori.</p></div><div className="flex gap-2"><button className="btn-secondary flex-1 sm:flex-none" onClick={exportCsv}><Download className="h-4 w-4" />Export CSV</button><button className="btn-primary flex-1 sm:flex-none" onClick={() => setModal({ open: true, transaction: null })}><ClipboardPlus className="h-4 w-4" />Catat Keluar/Masuk</button></div></header>
    <div className="mb-4 grid grid-cols-2 gap-3"><div className="panel border-l-4 border-l-emerald-500 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Catatan masuk aktif</p><p className="mt-2 text-2xl font-bold text-emerald-700">{incoming}</p></div><div className="panel border-l-4 border-l-blue-500 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">Catatan keluar aktif</p><p className="mt-2 text-2xl font-bold text-blue-700">{outgoing}</p></div></div>
    <section className="panel mb-4 p-4"><div className="relative"><Search className="absolute left-3.5 top-3 h-5 w-5 text-slate-400" /><input className="field pl-11" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari barang, kegiatan, peminjam, pencatat, atau alasan pembatalan..." /></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><select className="field" value={type} onChange={(e) => setType(e.target.value)}><option value="">Semua jenis</option>{["Masuk","Keluar","Kembali","Rusak","Hilang","Penyesuaian"].map((value) => <option key={value} value={value}>{value === "Penyesuaian" ? "Koreksi Stok" : value}</option>)}</select><select className="field" value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Semua kategori</option>{["Barang Habis Pakai","Barang Tetap","Konsumsi","Lainnya"].map((value) => <option key={value}>{value}</option>)}</select><select className="field" value={itemId} onChange={(e) => setItemId(e.target.value)}><option value="">Semua barang</option>{items.map((item) => <option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</select><select className="field" value={borrower} onChange={(e) => setBorrower(e.target.value)}><option value="">Semua peminjam/PIC</option>{borrowers.map((value) => <option key={value}>{value}</option>)}</select><input className="field" type="date" aria-label="Tanggal mulai" value={start} onChange={(e) => setStart(e.target.value)} /><input className="field" type="date" aria-label="Tanggal akhir" value={end} onChange={(e) => setEnd(e.target.value)} /><label className="flex h-11 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm font-medium"><input type="checkbox" className="accent-brand" checked={onlyOutstanding} onChange={(e) => setOnlyOutstanding(e.target.checked)} />Belum kembali</label></div></section>
    <div className="hidden md:block table-shell">{loading ? <div className="p-10 text-center text-sm text-slate-500">Memuat riwayat...</div> : <table className="table-base"><thead><tr><th><SortHeader label="Tanggal" field="transaction_date" sort={sort} direction={direction} onSort={onSort} /></th><th>Barang</th><th>Jenis</th><th><SortHeader label="Jumlah" field="quantity" sort={sort} direction={direction} onSort={onSort} /></th><th>Kegiatan / Peminjam</th><th>Dicatat oleh</th><th className="text-right">Aksi</th></tr></thead><tbody>{visible.map((row) => <tr key={row.id} className={row.reversed_at ? "opacity-60" : ""}><td><p className="font-semibold">{formatDateID(row.transaction_date)}</p><p className="text-xs text-slate-400">{new Date(row.created_at).toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" })}</p></td><td><p className="font-semibold">{row.item_name}</p><p className="text-xs text-slate-400">{row.item_code} · {row.item_category}</p></td><td>{getMovementBadge(row.type)}{row.reversed_at && <span className="ml-2 rounded-full bg-rose-100 px-2 py-1 text-xs font-bold text-rose-700">Dibatalkan</span>}{row.stocktake_id && <p className="mt-1 text-xs font-semibold text-violet-600">Final stock opname</p>}</td><td className={`font-bold ${row.reversed_at ? "line-through" : ""}`}>{row.type === "Penyesuaian" && row.quantity > 0 ? "+" : ""}{formatQty(row.quantity, row.item_unit)}</td><td><p>{row.activity_name || "—"}</p><p className="mt-0.5 text-xs text-slate-400">{row.handled_by || "—"}</p>{row.reversal_reason && <p className="mt-1 text-xs text-rose-700">Alasan: {row.reversal_reason}</p>}</td><td className="text-slate-600">@{row.recorded_by}</td><td><div className="flex justify-end gap-1">{canModify(row) && <><button className="grid h-9 w-9 place-items-center rounded-lg hover:bg-slate-100" onClick={() => setModal({ open: true, transaction: row })} aria-label="Ubah"><Pencil className="h-4 w-4" /></button><button className="grid h-9 w-9 place-items-center rounded-lg text-rose-600 hover:bg-rose-50" onClick={() => void reverse(row)} aria-label="Batalkan"><Ban className="h-4 w-4" /></button></>}</div></td></tr>)}</tbody></table>}</div>
    <div className="grid gap-3 md:hidden">{visible.map((row) => <article className={`panel p-4 ${row.reversed_at ? "opacity-60" : ""}`} key={row.id}><div className="flex justify-between gap-3"><div>{getMovementBadge(row.type)}{row.reversed_at && <span className="ml-2 text-xs font-bold text-rose-700">Dibatalkan</span>}<h2 className="mt-2 font-bold">{row.item_name}</h2><p className="text-xs text-slate-400">{row.item_code}</p></div><div className="text-right"><p className={`font-bold ${row.reversed_at ? "line-through" : ""}`}>{row.type === "Penyesuaian" && row.quantity > 0 ? "+" : ""}{formatQty(row.quantity, row.item_unit)}</p><p className="mt-1 text-xs text-slate-500">{formatDateID(row.transaction_date)}</p></div></div><div className="mt-3 border-t border-slate-100 pt-3 text-sm text-slate-600"><p>{row.activity_name || "Tanpa kegiatan"}</p><p className="mt-1 text-xs">Peminjam/PIC: {row.handled_by || "—"} · dicatat @{row.recorded_by}</p>{row.reversal_reason && <p className="mt-2 text-xs text-rose-700">Alasan: {row.reversal_reason}</p>}</div>{canModify(row) && <div className="mt-3 flex justify-end gap-2"><button className="btn-secondary min-h-9 px-3 py-1" onClick={() => setModal({ open: true, transaction: row })}><Pencil className="h-4 w-4" />Ubah</button><button className="grid h-9 w-9 place-items-center rounded-lg border border-rose-100 text-rose-600" onClick={() => void reverse(row)} aria-label="Batalkan"><Ban className="h-4 w-4" /></button></div>}</article>)}{!loading && visible.length === 0 && <div className="panel p-10 text-center text-sm text-slate-500">Belum ada catatan yang cocok dengan filter.</div>}</div>
    {filtered.length > 0 && <div className="mt-4 flex flex-col items-center justify-between gap-3 text-sm text-slate-500 sm:flex-row"><p>Menampilkan {(page - 1) * PAGE_SIZE + 1}–{Math.min(page * PAGE_SIZE, filtered.length)} dari {filtered.length} catatan</p><div className="flex gap-2"><button className="btn-secondary min-h-9 px-3 py-1" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Sebelumnya</button><span className="grid min-h-9 place-items-center px-2 font-semibold">{page} / {pages}</span><button className="btn-secondary min-h-9 px-3 py-1" disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>Berikutnya</button></div></div>}
    <InventoryTransactionModal open={modal.open} transaction={modal.transaction} onClose={() => setModal({ open: false, transaction: null })} />
  </div>;
}
