"use client";

import { useEffect, useRef, useState } from "react";
import { Camera, ScanLine } from "lucide-react";
import { ModalShell } from "./ModalShell";

type Detector={detect:(source:ImageBitmapSource)=>Promise<Array<{rawValue:string}>>};
declare global{interface Window{BarcodeDetector?:new(options?:{formats?:string[]})=>Detector;}}

export function BarcodeScannerModal({open,onClose,onDetected}:{open:boolean;onClose:()=>void;onDetected:(value:string)=>void}){const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const[manual,setManual]=useState("");const[error,setError]=useState("");useEffect(()=>{if(!open)return;let cancelled=false;async function start(){try{if(!window.BarcodeDetector)throw new Error("Pemindai kamera belum didukung browser ini. Masukkan kode secara manual.");stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});if(video.current){video.current.srcObject=stream.current;await video.current.play();}const detector=new window.BarcodeDetector({formats:["qr_code","code_128","code_39","ean_13","ean_8"]});const scan=async()=>{if(cancelled||!video.current)return;try{const result=await detector.detect(video.current);if(result[0]?.rawValue){onDetected(result[0].rawValue);onClose();return;}}catch{}window.setTimeout(scan,350);};void scan();}catch(err){setError(err instanceof Error?err.message:"Kamera tidak dapat dibuka");}}void start();return()=>{cancelled=true;stream.current?.getTracks().forEach((track)=>track.stop());stream.current=null;};},[open,onClose,onDetected]);function useManual(){if(!manual.trim())return;onDetected(manual.trim());onClose();}return <ModalShell open={open} onClose={onClose} title="Pindai kode barang" description="Arahkan kamera ke barcode atau QR yang berisi kode/SKU barang."><div className="p-5 sm:p-6"><div className="relative aspect-video overflow-hidden rounded-xl bg-slate-950"><video ref={video} muted playsInline className="h-full w-full object-cover"/><div className="pointer-events-none absolute inset-8 rounded-xl border-2 border-white/80"><ScanLine className="absolute left-1/2 top-1/2 h-10 w-10 -translate-x-1/2 -translate-y-1/2 text-white"/></div>{error&&<div className="absolute inset-0 grid place-items-center p-6 text-center text-sm text-white"><Camera className="mx-auto mb-3 h-8 w-8"/>{error}</div>}</div><div className="mt-4 flex gap-2"><input className="field" value={manual} onChange={(e)=>setManual(e.target.value)} onKeyDown={(e)=>{if(e.key==="Enter")useManual();}} placeholder="Atau ketik kode/SKU"/><button className="btn-primary" onClick={useManual}>Gunakan</button></div></div></ModalShell>}
