"use client";

import { useEffect, useRef, useState } from "react";
import { Camera, Loader2, Trash2, Upload } from "lucide-react";
import type { InventoryPhoto } from "./types";
import { useInventory } from "./InventoryContext";
import { authHeaders } from "@/lib/clientAuth";

export function InventoryPhotos({ itemId }: { itemId: string }) {
  const { toast } = useInventory(); const input=useRef<HTMLInputElement>(null); const [rows,setRows]=useState<InventoryPhoto[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [caption,setCaption]=useState("");
  async function load(){setLoading(true);try{const response=await fetch(`/api/inventory/photos?item_id=${encodeURIComponent(itemId)}`,{headers:authHeaders()});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setRows(payload.data??[]);}catch(err){toast(err instanceof Error?err.message:"Gagal memuat foto","error");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[itemId]);
  async function upload(file?:File){if(!file)return;setSaving(true);try{const dataUrl=await compressImage(file);const response=await fetch("/api/inventory/photos",{method:"POST",headers:authHeaders({"Content-Type":"application/json"}),body:JSON.stringify({item_id:itemId,data_url:dataUrl,caption})});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setCaption("");if(input.current)input.current.value="";await load();toast("Foto kondisi ditambahkan");}catch(err){toast(err instanceof Error?err.message:"Gagal mengunggah foto","error");}finally{setSaving(false);}}
  async function remove(id:string){if(!window.confirm("Hapus foto kondisi ini?"))return;const response=await fetch(`/api/inventory/photos?id=${encodeURIComponent(id)}`,{method:"DELETE",headers:authHeaders()});const payload=await response.json();if(!response.ok){toast(payload.error||"Gagal menghapus foto","error");return;}setRows((current)=>current.filter((row)=>row.id!==id));toast("Foto dihapus");}
  return <section className="border-t border-slate-100 p-5 sm:p-6"><div className="flex items-center gap-2"><Camera className="h-5 w-5 text-brand"/><h3 className="font-bold">Foto kondisi</h3><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-bold">{rows.length}</span></div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input className="field flex-1" value={caption} onChange={(e)=>setCaption(e.target.value)} placeholder="Keterangan foto (opsional)"/><input ref={input} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={(e)=>void upload(e.target.files?.[0])}/><button className="btn-secondary" disabled={saving} onClick={()=>input.current?.click()}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Upload className="h-4 w-4"/>}Tambah foto</button></div><p className="mt-2 text-xs text-slate-400">Foto otomatis diperkecil. Maksimal sekitar 2 MB per foto.</p>{loading?<p className="py-8 text-center text-sm text-slate-400">Memuat foto...</p>:rows.length?<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{rows.map((row)=><figure key={row.id} className="group relative overflow-hidden rounded-xl border border-slate-200 bg-slate-50"><img src={row.data_url} alt={row.caption||"Foto kondisi barang"} className="aspect-square w-full object-cover"/><figcaption className="p-2.5"><p className="truncate text-xs font-semibold">{row.caption||"Tanpa keterangan"}</p><p className="mt-0.5 text-[11px] text-slate-400">@{row.recorded_by}</p></figcaption><button onClick={()=>void remove(row.id)} className="absolute right-2 top-2 grid h-8 w-8 place-items-center rounded-lg bg-white/90 text-rose-600 opacity-100 shadow sm:opacity-0 sm:group-hover:opacity-100" aria-label="Hapus foto"><Trash2 className="h-4 w-4"/></button></figure>)}</div>:<div className="mt-4 rounded-xl border border-dashed border-slate-200 p-6 text-center text-sm text-slate-400">Belum ada foto kondisi.</div>}</section>;
}

async function compressImage(file:File){if(file.size>12_000_000)throw new Error("Ukuran foto asli terlalu besar");const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const context=canvas.getContext("2d");if(!context)throw new Error("Browser tidak dapat memproses foto");context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const result=canvas.toDataURL("image/jpeg",.78);if(result.length>2_800_000)throw new Error("Foto masih terlalu besar setelah diperkecil");return result;}
