"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, CalendarDays, Download, FileText, PackageSearch, Timer, TrendingDown } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useInventory } from "@/components/inventory/InventoryContext";
import { csvDownload, isExpiring, isLoanOverdue, isLowStock, outstandingLoans } from "@/components/inventory/inventoryUtils";
import { formatDateID, formatQty, formatRupiah } from "@/components/inventory/helpers";
import { exportInventoryReportPdf } from "@/components/inventory/reportPdf";
import { NotificationControl } from "@/components/inventory/NotificationControl";

const COLORS = ["#2463eb", "#06b6d4", "#8b5cf6", "#f59e0b"];
const dateString = (date: Date) => date.toISOString().slice(0, 10);

export default function ReportPage() {
  const { items, transactions, loading } = useInventory();
  const now = new Date(); const first = new Date(now.getFullYear(), now.getMonth() - 5, 1);
  const [start, setStart] = useState(dateString(first)); const [end, setEnd] = useState(dateString(now));
  const active = items.filter((row) => !row.is_archived);
  const periodRows = useMemo(() => transactions.filter((row) => !row.reversed_at && (!start || row.transaction_date >= start) && (!end || row.transaction_date <= end)), [transactions, start, end]);
  const months = useMemo(() => {
    const map = new Map<string, { key: string; label: string; Masuk: number; Keluar: number }>();
    periodRows.forEach((row) => { const key = row.transaction_date.slice(0, 7); const entry = map.get(key) ?? { key, label: new Date(`${key}-01T00:00:00`).toLocaleDateString("id-ID", { month: "short", year: "2-digit" }), Masuk: 0, Keluar: 0 }; if (["Masuk", "Kembali"].includes(row.type) || (row.type === "Penyesuaian" && row.quantity > 0)) entry.Masuk += 1; if (["Keluar", "Rusak", "Hilang"].includes(row.type) || (row.type === "Penyesuaian" && row.quantity < 0)) entry.Keluar += 1; map.set(key, entry); }); return [...map.values()].sort((a, b) => a.key.localeCompare(b.key));
  }, [periodRows]);
  const popular = useMemo(() => { const map = new Map<string, number>(); periodRows.filter((row) => row.type === "Keluar").forEach((row) => map.set(row.item_name, (map.get(row.item_name) ?? 0) + 1)); return [...map].sort((a, b) => b[1] - a[1]).slice(0, 7).map(([name, total]) => ({ name: name.length > 18 ? `${name.slice(0, 18)}…` : name, total })); }, [periodRows]);
  const values = useMemo(() => ["Barang Habis Pakai", "Barang Tetap", "Konsumsi", "Lainnya"].map((category) => ({ name: category, value: active.filter((row) => row.category === category).reduce((sum, row) => sum + Number(row.current_stock) * Number(row.purchase_price ?? 0), 0), count: active.filter((row) => row.category === category).length })), [active]);
  const restock = active.filter(isLowStock); const expiring = active.filter((row) => isExpiring(row, 30)); const loans = active.flatMap((item) => outstandingLoans(item.id, transactions).map((loan) => ({ ...loan, item })));
  const stagnant = active.filter((row) => { const last = row.last_movement_at ? new Date(row.last_movement_at) : new Date(row.created_at); return (Date.now() - last.getTime()) / 86400000 >= 90; });
  const totalStockValue = values.reduce((sum, row) => sum + row.value, 0); const outCount = periodRows.filter((row) => row.type === "Keluar").length;
  const overdueCount=loans.filter(isLoanOverdue).length;
  function preset(monthsBack: number) { const date = new Date(); date.setMonth(date.getMonth() - monthsBack + 1, 1); setStart(dateString(date)); setEnd(dateString(new Date())); }
  const exportCsv = () => csvDownload("laporan-inventaris.csv", ["Kategori", "Jumlah Barang", "Nilai Stok", "Perlu Restock", "Mendekati Kadaluarsa", "Sedang Dipinjam"], values.map((row) => [row.name, row.count, row.value, restock.filter((item) => item.category === row.name).length, expiring.filter((item) => item.category === row.name).length, active.filter((item) => item.category === row.name && item.outstanding > 0).length]));

  return <div className="mx-auto max-w-[1600px] p-4 sm:p-6 xl:p-8">
    <header className="mb-6 flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div><p className="text-sm font-semibold text-brand">Ringkasan & tindak lanjut</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Laporan Inventaris</h1><p className="mt-1 text-sm text-slate-500">Lihat pola pemakaian dan pekerjaan yang perlu dibereskan.</p></div><div className="flex flex-wrap gap-2"><div className="flex rounded-xl border border-slate-200 bg-white p-1"><button className="rounded-lg px-3 py-2 text-xs font-semibold hover:bg-slate-100" onClick={() => preset(1)}>Bulan ini</button><button className="rounded-lg px-3 py-2 text-xs font-semibold hover:bg-slate-100" onClick={() => preset(3)}>3 bulan</button><button className="rounded-lg px-3 py-2 text-xs font-semibold hover:bg-slate-100" onClick={() => preset(12)}>1 tahun</button></div><input className="field w-[145px]" type="date" value={start} onChange={(e) => setStart(e.target.value)} /><input className="field w-[145px]" type="date" value={end} onChange={(e) => setEnd(e.target.value)} /><NotificationControl restock={restock.length} expiry={expiring.length} overdue={overdueCount}/><button className="btn-secondary" onClick={exportCsv}><Download className="h-4 w-4" />CSV</button><button className="btn-primary" onClick={()=>exportInventoryReportPdf(items,transactions,start,end)}><FileText className="h-4 w-4"/>PDF</button></div></header>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric label="Nilai seluruh stok" value={formatRupiah(totalStockValue)} note={`${active.length} barang aktif`} /><Metric label="Transaksi keluar" value={`${outCount} catatan`} note="jumlah dipisah per satuan di grafik" /><Metric label="Pinjaman aktif" value={`${loans.length} catatan`} note="lihat jumlah per barang di bawah" /><Metric label="Butuh perhatian" value={formatQty(restock.length + expiring.length + overdueCount)} note="restock, expiry, terlambat" /> </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2">
      <ChartPanel title="Tren keluar-masuk" subtitle={`Jumlah catatan · ${formatDateID(start)} – ${formatDateID(end)}`} empty={!months.length}><ResponsiveContainer width="100%" height={290}><LineChart data={months} margin={{ top: 10, right: 12, left: -18, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="label" tick={{ fontSize: 12 }} stroke="#94a3b8" /><YAxis allowDecimals={false} tick={{ fontSize: 12 }} stroke="#94a3b8" /><Tooltip contentStyle={{ borderRadius: 12, borderColor: "#e2e8f0" }} /><Legend /><Line type="monotone" dataKey="Masuk" stroke="#10b981" strokeWidth={3} dot={{ r: 3 }} /><Line type="monotone" dataKey="Keluar" stroke="#2463eb" strokeWidth={3} dot={{ r: 3 }} /></LineChart></ResponsiveContainer></ChartPanel>
      <ChartPanel title="Barang paling sering keluar" subtitle="Berdasarkan frekuensi catatan pada periode" empty={!popular.length}><ResponsiveContainer width="100%" height={290}><BarChart data={popular} layout="vertical" margin={{ top: 5, right: 15, left: 15, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#e2e8f0" /><XAxis type="number" allowDecimals={false} tick={{ fontSize: 12 }} /><YAxis type="category" dataKey="name" width={110} tick={{ fontSize: 11 }} /><Tooltip contentStyle={{ borderRadius: 12, borderColor: "#e2e8f0" }} /><Bar dataKey="total" name="Frekuensi" fill="#2463eb" radius={[0, 6, 6, 0]} /></BarChart></ResponsiveContainer></ChartPanel>
      <ChartPanel title="Nilai stok per kategori" subtitle={`Total ${formatRupiah(totalStockValue)}`} empty={!totalStockValue}><ResponsiveContainer width="100%" height={290}><PieChart><Pie data={values.filter((row) => row.value > 0)} dataKey="value" nameKey="name" innerRadius={64} outerRadius={98} paddingAngle={3}>{values.map((_, index) => <Cell key={index} fill={COLORS[index % COLORS.length]} />)}</Pie><Tooltip formatter={(value) => formatRupiah(Number(value))} contentStyle={{ borderRadius: 12, borderColor: "#e2e8f0" }} /><Legend /></PieChart></ResponsiveContainer></ChartPanel>
      <section className="panel p-5"><h2 className="font-bold">Rekap kategori</h2><p className="mt-1 text-sm text-slate-500">Jumlah barang aktif dan nilai stok.</p><div className="mt-5 divide-y divide-slate-100">{values.map((row, index) => <div key={row.name} className="flex items-center gap-3 py-3"><span className="h-3 w-3 rounded-full" style={{ background: COLORS[index] }} /><div className="flex-1"><p className="text-sm font-semibold">{row.name}</p><p className="text-xs text-slate-400">{row.count} barang</p></div><p className="text-sm font-bold">{formatRupiah(row.value)}</p></div>)}</div></section>
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><FollowUp icon={<TrendingDown />} color="amber" title="Perlu restock" count={restock.length}>{restock.map((row) => <FollowRow key={row.id} title={row.name} detail={`${formatQty(row.current_stock, row.unit)} tersisa · minimum ${formatQty(row.min_stock, row.unit)}`} />)}</FollowUp><FollowUp icon={<CalendarDays />} color="rose" title="Mendekati kadaluarsa" count={expiring.length}>{expiring.map((row) => <FollowRow key={row.id} title={row.name} detail={`Kadaluarsa ${formatDateID(row.expiry_date)}`} />)}</FollowUp><FollowUp icon={<AlertTriangle />} color="blue" title="Pinjaman belum kembali" count={loans.length}>{loans.map((row) => <FollowRow key={row.id} title={`${row.item.name} · ${formatQty(row.remaining, row.item.unit)}`} detail={`${row.handled_by || "PIC belum diisi"} · ${formatDateID(row.expected_return_date)}`} danger={isLoanOverdue(row)} />)}</FollowUp><FollowUp icon={<Timer />} color="slate" title="Stok mengendap ≥ 90 hari" count={stagnant.length}>{stagnant.map((row) => <FollowRow key={row.id} title={row.name} detail={`Terakhir dipakai ${formatDateID(row.last_movement_at)} · ${formatQty(row.current_stock, row.unit)}`} />)}</FollowUp></div>
    {loading && <div className="fixed bottom-4 right-4 rounded-xl bg-navy px-4 py-3 text-sm font-semibold text-white shadow-xl">Memperbarui laporan...</div>}
  </div>;
}

function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <div className="panel p-4 sm:p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-2 truncate text-xl font-bold sm:text-2xl">{value}</p><p className="mt-1 hidden text-xs text-slate-400 sm:block">{note}</p></div>; }
function ChartPanel({ title, subtitle, empty, children }: { title: string; subtitle: string; empty: boolean; children: React.ReactNode }) { return <section className="panel p-4 sm:p-5"><h2 className="font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p><div className="mt-4 h-[290px]">{empty ? <div className="grid h-full place-items-center rounded-xl border border-dashed border-slate-200 text-sm text-slate-400"><PackageSearch className="mb-2 h-7 w-7" />Belum ada data pada periode ini.</div> : children}</div></section>; }
function FollowUp({ icon, color, title, count, children }: { icon: React.ReactNode; color: string; title: string; count: number; children: React.ReactNode }) { const colors: Record<string, string> = { amber: "bg-amber-50 text-amber-700", rose: "bg-rose-50 text-rose-700", blue: "bg-blue-50 text-blue-700", slate: "bg-slate-100 text-slate-700" }; return <section className="panel p-5"><div className="flex items-center gap-3"><div className={`grid h-10 w-10 place-items-center rounded-xl [&>svg]:h-5 [&>svg]:w-5 ${colors[color]}`}>{icon}</div><h2 className="flex-1 font-bold">{title}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{count}</span></div><div className="mt-4 max-h-64 divide-y divide-slate-100 overflow-y-auto">{count ? children : <p className="py-7 text-center text-sm text-slate-400">Tidak ada tindak lanjut.</p>}</div></section>; }
function FollowRow({ title, detail, danger }: { title: string; detail: string; danger?: boolean }) { return <div className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-semibold">{title}</p><p className={`mt-0.5 text-xs ${danger ? "font-semibold text-rose-600" : "text-slate-400"}`}>{detail}</p></div></div>; }
