"use client";

import { useEffect, useMemo, useState } from "react";
import { History, Search } from "lucide-react";
import type { InventoryAuditLog } from "@/components/inventory/types";
import { authHeaders } from "@/lib/clientAuth";

const labels: Record<string, string> = { create: "Dibuat", update: "Diubah", delete: "Dihapus", archive: "Diarsipkan", restore: "Dipulihkan", item: "Barang", transaction: "Catatan", photo: "Foto", user: "Pengguna", stocktake: "Stock opname" };

export default function AuditPage() {
  const [rows, setRows] = useState<InventoryAuditLog[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [entity, setEntity] = useState("");
  async function load() { setLoading(true); setError(""); try { const response=await fetch("/api/inventory/audit",{headers:authHeaders()}); const payload=await response.json(); if(!response.ok) throw new Error(payload.error); setRows(payload.data??[]); } catch(err){setError(err instanceof Error?err.message:"Gagal memuat audit log");} finally{setLoading(false);} }
  useEffect(()=>{void load();},[]);
  const filtered=useMemo(()=>rows.filter((row)=>(!entity||row.entity_type===entity)&&(!query||[row.entity_label,row.changed_by,row.action].some((v)=>v.toLowerCase().includes(query.toLowerCase())))),[rows,entity,query]);
  return <div className="mx-auto max-w-[1400px] p-4 sm:p-6 xl:p-8"><header><p className="text-sm font-semibold text-brand">Akuntabilitas</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Audit Aktivitas</h1><p className="mt-1 text-sm text-slate-500">Jejak perubahan, pengarsipan, dan penghapusan data inventaris.</p></header><div className="panel mt-6 flex flex-col gap-3 p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3.5 top-3 h-5 w-5 text-slate-400"/><input className="field pl-11" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Cari barang, aksi, atau username..."/></div><select className="field sm:w-48" value={entity} onChange={(e)=>setEntity(e.target.value)}><option value="">Semua data</option><option value="item">Barang</option><option value="transaction">Catatan</option><option value="photo">Foto</option><option value="user">Pengguna</option><option value="stocktake">Stock opname</option></select></div><div className="mt-4 table-shell"><table className="table-base"><thead><tr><th>Waktu</th><th>Data</th><th>Aksi</th><th>Oleh</th><th>Perubahan</th></tr></thead><tbody>{filtered.map((row)=><tr key={row.id}><td className="whitespace-nowrap">{new Date(row.created_at).toLocaleString("id-ID")}</td><td><p className="font-semibold">{row.entity_label}</p><p className="text-xs text-slate-400">{labels[row.entity_type]}</p></td><td><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{labels[row.action]}</span></td><td className="font-medium">@{row.changed_by}</td><td className="max-w-md text-xs text-slate-500">{describeChange(row)}</td></tr>)}</tbody></table>{loading&&<div className="p-10 text-center text-sm text-slate-500">Memuat audit log...</div>}{error&&<div className="p-10 text-center"><p className="text-sm text-rose-600">{error}</p><button className="btn-secondary mt-3" onClick={()=>void load()}>Coba lagi</button></div>}{!loading&&!error&&!filtered.length&&<div className="p-10 text-center text-sm text-slate-500"><History className="mx-auto mb-3 h-7 w-7 text-slate-300"/>Belum ada aktivitas yang cocok.</div>}</div></div>;
}

function describeChange(row: InventoryAuditLog){if(row.action==="create")return "Data baru dibuat";if(row.action==="delete")return "Data dihapus permanen";const old=row.old_data??{};const next=row.new_data??{};const ignored=new Set(["updated_at","updated_by"]);const keys=[...new Set([...Object.keys(old),...Object.keys(next)])].filter((key)=>!ignored.has(key)&&JSON.stringify(old[key])!==JSON.stringify(next[key]));return keys.length?`Kolom berubah: ${keys.slice(0,6).join(", ")}${keys.length>6?"…":""}`:"Metadata diperbarui";}
