"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, CheckCircle2, ClipboardCheck, Loader2, Plus, Save, Trash2, XCircle } from "lucide-react";
import type { InventoryStocktake, InventoryStocktakeLine } from "@/components/inventory/types";
import { authHeaders } from "@/lib/clientAuth";
import { useInventory } from "@/components/inventory/InventoryContext";
import { ModalShell } from "@/components/inventory/ModalShell";
import { formatQty } from "@/components/inventory/helpers";

const statusLabel={draft:"Berjalan",completed:"Selesai",cancelled:"Dibatalkan"};

export default function StocktakesPage(){
  const{user,toast,refetchInventory}=useInventory();
  const[rows,setRows]=useState<InventoryStocktake[]>([]);const[selected,setSelected]=useState<InventoryStocktake|null>(null);const[lines,setLines]=useState<InventoryStocktakeLine[]>([]);
  const[counts,setCounts]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[creating,setCreating]=useState(false);const[form,setForm]=useState({title:"",notes:""});
  async function api(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:authHeaders({"Content-Type":"application/json",...(options?.headers??{})})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"Terjadi kesalahan");return payload;}
  async function loadList(preferred?:string){setLoading(true);try{const payload=await api("/api/inventory/stocktakes");const next=payload.data??[];setRows(next);const id=preferred??selected?.id??next.find((row:InventoryStocktake)=>row.status==="draft")?.id??next[0]?.id;if(id){const match=next.find((row:InventoryStocktake)=>row.id===id)??null;setSelected(match);if(match)await loadLines(match.id);}else{setSelected(null);setLines([]);}}catch(err){toast(err instanceof Error?err.message:"Gagal memuat stock opname","error");}finally{setLoading(false);}}
  async function loadLines(id:string){const payload=await api(`/api/inventory/stocktakes?id=${encodeURIComponent(id)}`);const next:InventoryStocktakeLine[]=payload.data??[];setLines(next);setCounts(Object.fromEntries(next.map((line)=>[line.item_id,line.counted_stock===null?"":String(line.counted_stock)])));}
  useEffect(()=>{void loadList();},[]);
  const changed=useMemo(()=>lines.some((line)=>counts[line.item_id]!== (line.counted_stock===null?"":String(line.counted_stock))),[lines,counts]);
  async function create(e:React.FormEvent){e.preventDefault();setSaving(true);try{const payload=await api("/api/inventory/stocktakes",{method:"POST",body:JSON.stringify(form)});setCreating(false);setForm({title:"",notes:""});await loadList(payload.id);toast("Stock opname dimulai");}catch(err){toast(err instanceof Error?err.message:"Gagal membuat stock opname","error");}finally{setSaving(false);}}
  async function save(){if(!selected)return;const payload=lines.map((line)=>({item_id:line.item_id,counted_stock:counts[line.item_id]===""?null:Number(counts[line.item_id])}));if(payload.some((line)=>line.counted_stock===null||!Number.isFinite(line.counted_stock)||Number(line.counted_stock)<0)){toast("Isi stok fisik semua barang dengan angka nol atau lebih","error");return false;}setSaving(true);try{await api("/api/inventory/stocktakes",{method:"PUT",body:JSON.stringify({action:"save_lines",id:selected.id,lines:payload})});await loadLines(selected.id);await loadList(selected.id);toast("Hitungan fisik disimpan");return true;}catch(err){toast(err instanceof Error?err.message:"Gagal menyimpan hitungan","error");return false;}finally{setSaving(false);}}
  async function finish(){if(!selected||!window.confirm("Selesaikan stock opname dan terapkan seluruh selisih ke stok?"))return;const saved=await save();if(!saved)return;setSaving(true);try{await api("/api/inventory/stocktakes",{method:"PUT",body:JSON.stringify({action:"complete",id:selected.id})});await refetchInventory();await loadList(selected.id);toast("Stock opname selesai dan stok telah disesuaikan");}catch(err){toast(err instanceof Error?err.message:"Gagal menyelesaikan stock opname","error");}finally{setSaving(false);}}
  async function action(action:"cancel"|"delete"){if(action==="delete"){toast("Riwayat stock opname tidak dapat dihapus; status dibatalkan tetap disimpan","error");return;}if(!selected||!window.confirm("Batalkan stock opname ini? Riwayat sesi tetap disimpan."))return;setSaving(true);try{await api("/api/inventory/stocktakes",{method:"PUT",body:JSON.stringify({action,id:selected.id})});setSelected(null);await loadList();toast("Stock opname dibatalkan; riwayat tetap tersimpan");}catch(err){toast(err instanceof Error?err.message:"Tindakan gagal","error");}finally{setSaving(false);}}
  function select(row:InventoryStocktake){setSelected(row);void loadLines(row.id);}

  return <div className="mx-auto max-w-[1450px] p-4 sm:p-6 xl:p-8"><header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-brand">Kontrol stok fisik</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Stock Opname</h1><p className="mt-1 text-sm text-slate-500">Hitung barang, tinjau selisih, lalu terapkan penyesuaian secara terkontrol.</p></div>{user.role==="admin"&&<button className="btn-primary" disabled={rows.some((row)=>row.status==="draft")} onClick={()=>setCreating(true)}><Plus className="h-4 w-4"/>Mulai stock opname</button>}</header>
    {rows.some((row)=>row.status==="draft")&&<div className="mt-4 flex gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><AlertTriangle className="h-5 w-5 shrink-0"/><div><p className="font-bold">Stok sedang dibekukan</p><p className="mt-1">Master barang dan seluruh pergerakan stok ditolak sampai sesi selesai atau dibatalkan.</p></div></div>}
    <div className="mt-6 grid gap-4 xl:grid-cols-[330px_1fr]"><aside className="panel h-fit overflow-hidden"><div className="border-b border-slate-100 p-4"><h2 className="font-bold">Riwayat sesi</h2></div>{loading?<p className="p-8 text-center text-sm text-slate-400">Memuat...</p>:rows.length?<div className="divide-y divide-slate-100">{rows.map((row)=><button key={row.id} onClick={()=>select(row)} className={`w-full p-4 text-left hover:bg-slate-50 ${selected?.id===row.id?"bg-blue-50/70":""}`}><div className="flex items-start justify-between gap-2"><p className="font-semibold">{row.title}</p><span className={`rounded-full px-2 py-1 text-xs font-bold ${row.status==="completed"?"bg-emerald-50 text-emerald-700":row.status==="cancelled"?"bg-slate-100 text-slate-600":"bg-amber-50 text-amber-700"}`}>{statusLabel[row.status]}</span></div><p className="mt-2 text-xs text-slate-500">{Number(row.counted_items)}/{Number(row.total_items)} dihitung · {Number(row.variance_items)} selisih</p><p className="mt-1 text-xs text-slate-400">Dibuka @{row.created_by}</p></button>)}</div>:<p className="p-8 text-center text-sm text-slate-400">Belum ada stock opname.</p>}</aside>
      <section className="panel min-w-0 overflow-hidden">{!selected?<div className="grid min-h-80 place-items-center p-8 text-center"><div><ClipboardCheck className="mx-auto h-10 w-10 text-slate-300"/><p className="mt-3 font-semibold">Pilih atau mulai stock opname</p></div></div>:<><div className="flex flex-col justify-between gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center"><div><h2 className="text-lg font-bold">{selected.title}</h2><p className="mt-1 text-sm text-slate-500">{selected.notes||"Tanpa catatan"}</p></div>{selected.status==="draft"&&<div className="flex flex-wrap gap-2"><button className="btn-secondary" disabled={saving||!changed} onClick={()=>void save()}>{saving?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Simpan</button>{user.role==="admin"&&<><button className="btn-primary" disabled={saving} onClick={()=>void finish()}><CheckCircle2 className="h-4 w-4"/>Selesaikan</button><button className="btn-secondary text-rose-600" disabled={saving} onClick={()=>void action("cancel")}><XCircle className="h-4 w-4"/>Batalkan</button></>}</div>}{selected.status==="cancelled"&&user.role==="admin"&&<button className="btn-secondary text-rose-600" onClick={()=>void action("delete")}><Trash2 className="h-4 w-4"/>Hapus</button>}</div><div className="overflow-x-auto"><table className="table-base min-w-[720px]"><thead><tr><th>Barang</th><th>Stok sistem</th><th>Stok fisik</th><th>Selisih</th><th>Penghitung</th></tr></thead><tbody>{lines.map((line)=>{const value=counts[line.item_id];const numeric=value===""?null:Number(value);const difference=numeric===null?null:numeric-Number(line.system_stock);return <tr key={line.item_id}><td><p className="font-semibold">{line.item_name}</p><p className="text-xs font-mono text-slate-400">{line.item_code}</p></td><td className="font-semibold">{formatQty(Number(line.system_stock),line.item_unit)}</td><td>{selected.status==="draft"?<div className="relative w-40"><input className="field pr-14" type="number" min="0" step="any" value={value??""} onChange={(e)=>setCounts({...counts,[line.item_id]:e.target.value})}/><span className="absolute inset-y-0 right-3 flex items-center text-xs text-slate-400">{line.item_unit}</span></div>:formatQty(Number(line.counted_stock??0),line.item_unit)}</td><td><span className={`font-bold ${difference===null||difference===0?"text-slate-500":difference>0?"text-emerald-700":"text-rose-700"}`}>{difference===null?"—":`${difference>0?"+":""}${formatQty(difference,line.item_unit)}`}</span></td><td className="text-sm text-slate-500">{line.counted_by?`@${line.counted_by}`:"—"}</td></tr>;})}</tbody></table></div></>}</section>
    </div>
    <ModalShell open={creating} onClose={()=>setCreating(false)} title="Mulai stock opname" description="Stok semua barang aktif akan dipotret sebagai nilai awal."><form onSubmit={create}><div className="space-y-4 p-5 sm:p-6"><div><label className="field-label">Judul *</label><input className="field" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} placeholder="Contoh: Stock opname September 2026" autoFocus/></div><div><label className="field-label">Catatan</label><textarea className="field min-h-24" value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></div></div><footer className="flex justify-end gap-3 border-t border-slate-100 bg-slate-50/60 px-5 py-4"><button type="button" className="btn-secondary" onClick={()=>setCreating(false)}>Batal</button><button className="btn-primary" disabled={saving||!form.title.trim()}>Mulai</button></footer></form></ModalShell>
  </div>;
}
