"use client";

import { useEffect, useState } from "react";
import { Edit3, Eye, EyeOff, KeyRound, Loader2, LogOut, Plus, ShieldCheck, UserRound } from "lucide-react";
import type { AppUser } from "@/components/inventory/types";
import { authHeaders, clearClientSession } from "@/lib/clientAuth";
import { useInventory } from "@/components/inventory/InventoryContext";
import { ModalShell } from "@/components/inventory/ModalShell";

const blankCreate={username:"",full_name:"",password:"",role:"member" as "admin"|"member"};

export function UserManagement(){
  const{toast,user}=useInventory();
  const[rows,setRows]=useState<AppUser[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
  const[show,setShow]=useState(false);const[error,setError]=useState("");const[form,setForm]=useState(blankCreate);
  const[editing,setEditing]=useState<AppUser|null>(null);const[editForm,setEditForm]=useState({full_name:"",role:"member" as "admin"|"member",is_active:true});
  const[resetting,setResetting]=useState<AppUser|null>(null);const[newPassword,setNewPassword]=useState("");

  async function request(body:unknown){const response=await fetch("/api/users",{method:"PUT",headers:authHeaders({"Content-Type":"application/json"}),body:JSON.stringify(body)});const payload=await response.json();if(!response.ok)throw new Error(payload.error);return payload;}
  async function load(){setLoading(true);setError("");try{const response=await fetch("/api/users",{headers:authHeaders()});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setRows(payload.data??[]);}catch(err){setError(err instanceof Error?err.message:"Gagal memuat pengguna");}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function create(e:React.FormEvent){e.preventDefault();setError("");if(!form.username.trim()||form.password.length<8){setError("Username wajib diisi dan password minimal 8 karakter");return;}setSaving(true);try{const response=await fetch("/api/users",{method:"POST",headers:authHeaders({"Content-Type":"application/json"}),body:JSON.stringify(form)});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setForm(blankCreate);await load();toast("Pengguna berhasil dibuat");}catch(err){setError(err instanceof Error?err.message:"Gagal membuat pengguna");}finally{setSaving(false);}}
  function openEdit(row:AppUser){setEditing(row);setEditForm({full_name:row.full_name??"",role:row.role,is_active:row.is_active});}
  async function saveEdit(e:React.FormEvent){e.preventDefault();if(!editing)return;setSaving(true);try{await request({action:"update",id:editing.id,...editForm});setEditing(null);await load();toast("Pengguna berhasil diperbarui");}catch(err){toast(err instanceof Error?err.message:"Gagal memperbarui pengguna","error");}finally{setSaving(false);}}
  async function resetPassword(e:React.FormEvent){e.preventDefault();if(!resetting||newPassword.length<8){toast("Password minimal 8 karakter","error");return;}setSaving(true);try{await request({action:"reset_password",id:resetting.id,password:newPassword});if(resetting.username===user.username){clearClientSession();window.location.href="/login";return;}setResetting(null);setNewPassword("");await load();toast("Password direset dan semua sesi pengguna dicabut");}catch(err){toast(err instanceof Error?err.message:"Gagal mereset password","error");}finally{setSaving(false);}}
  async function revoke(row:AppUser){if(!window.confirm(`Keluarkan @${row.username} dari semua perangkat?`))return;setSaving(true);try{await request({action:"revoke_sessions",id:row.id});if(row.username===user.username){clearClientSession();window.location.href="/login";return;}await load();toast("Semua sesi pengguna dicabut");}catch(err){toast(err instanceof Error?err.message:"Gagal mencabut sesi","error");}finally{setSaving(false);}}

  return <div className="mx-auto max-w-[1200px] p-4 sm:p-6 xl:p-8">
    <header><p className="text-sm font-semibold text-brand">Khusus admin</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Kelola Pengguna</h1><p className="mt-1 text-sm text-slate-500">Buat akun, ubah akses, reset password, dan cabut sesi perangkat.</p></header>
    <div className="mt-6 grid gap-4 lg:grid-cols-[360px_1fr]">
      <form onSubmit={create} className="panel h-fit p-5"><div className="flex items-center gap-2"><Plus className="h-5 w-5 text-brand"/><h2 className="font-bold">Buat pengguna</h2></div>{error&&<div className="mt-4 rounded-xl border border-rose-100 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<div className="mt-5 space-y-4"><div><label className="field-label">Nama lengkap</label><input className="field" value={form.full_name} onChange={(e)=>setForm({...form,full_name:e.target.value})}/></div><div><label className="field-label">Username *</label><input className="field" autoComplete="off" value={form.username} onChange={(e)=>setForm({...form,username:e.target.value})}/></div><div><label className="field-label">Password *</label><div className="relative"><input className="field pr-11" type={show?"text":"password"} autoComplete="new-password" value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})}/><button type="button" onClick={()=>setShow((value)=>!value)} className="absolute inset-y-0 right-0 grid w-11 place-items-center text-slate-400" aria-label="Lihat password">{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div><p className="mt-1 text-xs text-slate-400">Minimal 8 karakter.</p></div><div><label className="field-label">Role *</label><select className="field" value={form.role} onChange={(e)=>setForm({...form,role:e.target.value as "admin"|"member"})}><option value="member">Member — inventaris</option><option value="admin">Admin — termasuk pengguna</option></select></div><button className="btn-primary w-full" disabled={saving}>{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}Buat pengguna</button></div></form>
      <section className="panel overflow-hidden"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Daftar pengguna</h2><p className="mt-1 text-sm text-slate-500">{rows.length} akun terdaftar</p></div>{loading?<div className="p-10 text-center text-sm text-slate-400">Memuat pengguna...</div>:<div className="divide-y divide-slate-100">{rows.map((row)=><div key={row.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:px-5"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${row.role==="admin"?"bg-blue-50 text-brand":"bg-slate-100 text-slate-600"}`}>{row.role==="admin"?<ShieldCheck className="h-5 w-5"/>:<UserRound className="h-5 w-5"/>}</div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{row.full_name||row.username}{row.username===user.username&&<span className="ml-2 text-xs text-brand">Anda</span>}</p><p className="truncate text-xs text-slate-400">@{row.username} · {Number(row.active_sessions)} sesi aktif</p></div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${row.role==="admin"?"bg-blue-50 text-blue-700":"bg-slate-100 text-slate-600"}`}>{row.role==="admin"?"Admin":"Member"}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${row.is_active?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{row.is_active?"Aktif":"Nonaktif"}</span><button className="btn-secondary px-2.5" onClick={()=>openEdit(row)} aria-label={`Edit ${row.username}`}><Edit3 className="h-4 w-4"/></button><button className="btn-secondary px-2.5" onClick={()=>{setResetting(row);setNewPassword("");}} aria-label={`Reset password ${row.username}`}><KeyRound className="h-4 w-4"/></button><button className="btn-secondary px-2.5" disabled={!Number(row.active_sessions)||saving} onClick={()=>void revoke(row)} aria-label={`Cabut sesi ${row.username}`}><LogOut className="h-4 w-4"/></button></div></div>)}</div>}</section>
    </div>
    <ModalShell open={Boolean(editing)} onClose={()=>setEditing(null)} title="Edit pengguna" description={editing?`@${editing.username}`:""}><form onSubmit={saveEdit}><div className="space-y-4 p-5 sm:p-6"><div><label className="field-label">Nama lengkap</label><input className="field" value={editForm.full_name} onChange={(e)=>setEditForm({...editForm,full_name:e.target.value})}/></div><div><label className="field-label">Role</label><select className="field" disabled={editing?.username===user.username} value={editForm.role} onChange={(e)=>setEditForm({...editForm,role:e.target.value as "admin"|"member"})}><option value="member">Member</option><option value="admin">Admin</option></select></div><label className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" disabled={editing?.username===user.username} checked={editForm.is_active} onChange={(e)=>setEditForm({...editForm,is_active:e.target.checked})}/><span className="text-sm font-semibold">Akun aktif</span></label>{editing?.username===user.username&&<p className="text-xs text-slate-500">Role dan status akun sendiri tidak dapat diubah.</p>}</div><footer className="flex justify-end gap-3 border-t border-slate-100 bg-slate-50/60 px-5 py-4"><button type="button" className="btn-secondary" onClick={()=>setEditing(null)}>Batal</button><button className="btn-primary" disabled={saving}>Simpan perubahan</button></footer></form></ModalShell>
    <ModalShell open={Boolean(resetting)} onClose={()=>setResetting(null)} title="Reset password" description={resetting?`Password baru untuk @${resetting.username}`:""}><form onSubmit={resetPassword}><div className="p-5 sm:p-6"><label className="field-label">Password baru</label><input className="field" type="password" autoComplete="new-password" value={newPassword} onChange={(e)=>setNewPassword(e.target.value)} autoFocus/><p className="mt-2 text-xs text-slate-500">Minimal 8 karakter. Semua sesi pengguna akan langsung dicabut.</p></div><footer className="flex justify-end gap-3 border-t border-slate-100 bg-slate-50/60 px-5 py-4"><button type="button" className="btn-secondary" onClick={()=>setResetting(null)}>Batal</button><button className="btn-primary" disabled={saving||newPassword.length<8}>Reset password</button></footer></form></ModalShell>
  </div>;
}
